# Generated by Django 2.2.6 on 2021-02-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='event_images/')),
            ],
        ),
    ]
